### ISSUE TITLE
Unable to read the vignettes

### ISSUE THREAD

**Issue by GuiSeSanz** [WWXkenmo/ICAnet#2]
Hi!

I just installed the packages and I was trying to read the vignettes but it was impossible!
They are not visible in github nor rdrr.io.
So I can't run it at all as I don't know how to start...

Thanks!

**Comment by WWXkenmo** [comment]
Hi!
I just checked the vignettes and noticed that the link to view the vignettes will be influenced by your web browser, but that's ok, I have transformed my vignettes into PDF format, now you can check them in https://github.com/WWXkenmo/ICAnet/tree/master/vignettes
Hope this response is helpful.

**Comment by GuiSeSanz** [comment]
Great!
Thanks very much!
