### ISSUE TITLE
clusters overlap in UMAP

### ISSUE THREAD

**Issue by TangentDeng** [WWXkenmo/ICAnet#5]
Hi, me again! I run the ICAnet result in Seurat way.
ICAnet <- FindClusters(ICAnet,graph.name = 'IcaNet_TF_snn',algorithm = 4,resolution = 0.6)
ICAnet <- RunUMAP(ICAnet,reduction = 'pca',seed.use = 123,graph = 'IcaNet_TF_snn',assay = 'IcaNet_TF',min.dist = 0.01,n.neighbors = 40)
DimPlot(ICAnet,label = T,group.by = 'IcaNet_TF_snn_res.0.6',split.by = 'orig.ident')
The clusters overlap in 1,2,3,4,8. Can it be solved? Thanks.
![image](https://user-images.githubusercontent.com/22614959/130641839-4c0866c2-233f-44b9-9658-6b2c45cd441e.png)

**Comment by WWXkenmo** [comment]
Hi!
  If the clustering results and feature reductions results are inconsistent, try to make sure you using the same graph to perform both reductions and cell clustering. I was wondering if you used the "pca" reductions to construct 'IcaNet_TF_snn'?
